<?php
/**
 * @see Wf_CustomerBalance_Block_Adminhtml_Customer_Edit_Tab_Customerbalance_Balance
 */
?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-account"><?php echo $this->helper('wf_customerbalance')->__('Store Credit Balance')?></h4>
    </div>
    <div class="fieldset">
        <?php if($this->isSingleBalanceMode()): ?>
            <?php
                $creditAmount = $this->getSingleCreditAmount();
            ?>
            <p><?php echo $this->__("This customer has a <b>%s</b> credit balance.", $creditAmount); ?></p>
        <?php else: ?>
            <?php echo $this->getChildHtml('grid')?>
            <?php echo $this->getDeleteOrphanBalancesButton() ?>
        <?php endif; ?>
    </div>
</div>
