<?php 
    $autoRefundEnabled = Mage::helper('wf_customerbalance')->isAutoRefundEnabled();
    $boxChecked = $autoRefundEnabled || $this->mustRefundToCustomerBalance() || $this->getReturnValue() > 0; 
    $confirmMsg = $this->__("Are you sure you do not want any part of this refund to go back to the user\\'s store credit balance?");
?>
<?php if ($this->canRefundToCustomerBalance()): ?>
    <p>
        <label for="creditmemo_customerbalance_return_enable">
            <?php if($this->mustRefundToCustomerBalance()): ?>
                <?php echo $this->__("<strong>Note:</strong> The credit memo will refund the order total (less any adjustments) back to the customer's store credit balance and the remainder will be refunded to the customer's original payment method.") ?>
            <?php else: ?>
                <?php echo $this->__('Refund to Store Credit') ?>
            <?php endif; ?>
        </label>
        <input type="hidden" name="creditmemo[refund_customerbalance_return_enable]" 
                value="<?php if($this->mustRefundToCustomerBalance()): ?>1<?php else: ?>0<?php endif; ?>">
        <input type="<?php if($this->mustRefundToCustomerBalance()): ?>hidden<?php else: ?>checkbox<?php endif; ?>" 
                name="creditmemo[refund_customerbalance_return_enable]" 
                value="1" 
                id="creditmemo_customerbalance_return_enable"
                <?php if ($boxChecked): ?> checked="checked"<?php endif ?>>
        <input type="<?php if($this->mustRefundToCustomerBalance()): ?>hidden<?php else: ?>text<?php endif; ?>" 
            name="creditmemo[refund_customerbalance_return]" 
            value="<?php echo $this->getReturnValue(); ?>" id="creditmemo_customerbalance_return" 
            class="input-text not-negative-amount" style="width: 60px; text-align: right;">
        <?php if(!$this->mustRefundToCustomerBalance()): ?>
        <script type="text/javascript">
        //<![CDATA[
            
            function toggleCustomerBalanceRefundAmount(doConfirm) {
                if (typeof doConfirm === 'undefined') {
                    doConfirm = true;
                }
                var doConfirmUncheck = doConfirm && <?php echo $boxChecked ? 'true': 'false'; ?>;
                if ($('creditmemo_customerbalance_return_enable').checked) {
                    $('creditmemo_customerbalance_return').disabled = false;
                } else {
                    if (doConfirmUncheck && !confirm('<?php echo htmlspecialchars($confirmMsg); ?>')) {
                        $('creditmemo_customerbalance_return_enable').checked = true;
                        return false;
                    }
                    $('creditmemo_customerbalance_return').disabled = true;
                }
            }
            Event.observe($('creditmemo_customerbalance_return_enable'), 'change', toggleCustomerBalanceRefundAmount);
            toggleCustomerBalanceRefundAmount(false);
        //]]>
        </script>
        <?php endif; ?>
    </p>
<?php endif; ?>
